### PR TITLE
Wrenching a wireless connector keeps its color.

### PR DESCRIPTION
**Pull request by AbdielKavash**
This PR contains two changes to AE wireless connectors:
* Dismantling a colored connector by right-clicking with a wrench now keeps its color in the player's inventory and when placed.
* Colored but not connected connectors display their color, but faded out, instead of being black regardless of color.

Breaking a connector with a pickaxe (or another tool) reverts it to the original uncolored state.

Demonstration:

https://github.com/user-attachments/assets/35cae67f-e827-41af-9bfd-de0ad541a192

All active and inactive colors:

This is my first time writing Scala, please review the code and let me know if I did something wrong.

### CODE REVIEW

**Comment by Ruling-0** [comment]
It's minor but somewhat related, would this be a good/easy opportunity to swap the color of magenta and purple? I'm pretty sure they are currently backwards, and it seemed like quite a few people on the Discord agreed https://discord.com/channels/181078474394566657/181078474394566657/1299205073724899420

**Comment by AbdielKavash** [comment]
Oh, they're definitely backwards!

Left, magenta; right, purple.

**Comment by Alexdoru** [comment]
are we sure we want to do that ? What if I want it to not keep it's color when I break it ? Now I have to place it, decolor it, break it again, that's annoying

**Comment by ALongStringOfNumbers** [comment]
> are we sure we want to do that ? What if I want it to not keep it's color when I break it ? Now I have to place it, decolor it, break it again, that's annoying

It says in the initial post that breaking it with a pickaxe will make it lose the color, so when you initially break it, just use a pickaxe/non-wrench

**Comment by Alexdoru** [comment]
> > are we sure we want to do that ? What if I want it to not keep it's color when I break it ? Now I have to place it, decolor it, break it again, that's annoying
> 
> It says in the initial post that breaking it with a pickaxe will make it lose the color, so when you initially break it, just use a pickaxe/non-wrench

I should learn how to read sometime! It looks useful

**Review by OneEyeMaker — APPROVED** [review]

**Pull request merged**
