### PR TITLE
Change energy consumption on wireless connector

### PR DESCRIPTION
**Pull request by GTNH-Colen**
Changed the consumption from x^2 to x * ln(x^2 + 3) where x is the distance between connectors.

### CODE REVIEW

**Comment by GTNH-Colen** [comment]
Think this is done now.

**Comment by GTNH-Colen** [comment]
@Dream-Master

**Comment by Prometheus0000** [comment]
You didn't assign a reviewer

**Comment by GTNH-Colen** [comment]
Ahhh, my bad.

**Review by Dream-Master — APPROVED** [review]

**Comment by Prometheus0000** [comment]
BTW, if it ways the previous formula in the quest, you should probably edit the quest to show the new one or make a ticket about it. In a way that normal people can understand, because this is incomprehensible.

**Comment by GTNH-Colen** [comment]
> BTW, if it ways the previous formula in the quest, you should probably edit the quest to show the new one or make a ticket about it. In a way that normal people can understand, because this is incomprehensible.

It's really not that complicated, I just introduced a log to slow the growth rate a bit.

**Pull request merged**
